### PR TITLE
🐎 RLE for memory in snapshots

### PR DESCRIPTION
**Pull request by MaartenS11**
Currently only uses run length encoding to transfer snapshots from the microcontroller to the computer, not the other way around. The VSCode plugin will need changes to be able to reconstruct  the actual bytes in memory.

### CODE REVIEW

**Comment by tolauwae** [comment]
**💥 Breaking change warning**
TOPLLab/WARDuino-VSCode will not be able to parse the new snapshots

**Comment by tolauwae** [comment]
I want to add this change for the new major release @MaartenS11
If you need any help, you can ping me

**Comment by tolauwae** [comment]
@MaartenS11 so you implemented a simple run-length encoding yourselves? And it just shortens consecutive strings as the pattern and number of occurrences separated by a comma? `pattern,count`
And it does this every time, even when the count is one.

Is that correct?

**Comment by MaartenS11** [comment]
> @MaartenS11 so you implemented a simple run-length encoding yourselves? And it just shortens consecutive strings as the pattern and number of occurrences separated by a comma? `pattern,count` And it does this every time, even when the count is one.
> 
> Is that correct?

It's `count,pattern` but besides that, yes that's how it works. You can't really not do it for sequences of length 1 because you have no way to identify if the byte is a count or the pattern itself.

**Review by tolauwae — APPROVED** [review]
Looks good. Although I would move the RLE to separate util functions.
But can be merged as is.

**Pull request merged**
