### PR TITLE
🚑 Hotfix #251

### PR DESCRIPTION
**Pull request by tolauwae**

### CODE REVIEW

**Comment by MaartenS11** [comment]
This fix mostly works but for some reason it causes console spam with some programs. This console spam disappears once a character is sent over serial. If I add a tiny delay this console spam doesn't appear at all. Delay causes a yield but also allows tasks with a priority lower than the current task to take over but this seems like a very strange fix.
```c++
    Serial.println("\nFree heap:");
    Serial.println(ESP.getFreeHeap());

    delay(1);
    
    wac->run_module(m);
```

**Comment by tolauwae** [comment]
> This fix mostly works but for some reason it causes console spam with some programs. 

@MaartenS11 can you give an example program to reproduce the bug?

**Comment by MaartenS11** [comment]
> > This fix mostly works but for some reason it causes console spam with some programs.
> 
> @MaartenS11 can you give an example program to reproduce the bug?

I got the console spam when just running blink without the tiny delay.

**Comment by tolauwae** [comment]
> I got the console spam when just running blink (from `tutorials/wat/main/blink.wat`) without the tiny delay.

The blink example works on my devices. Can you upload the `.wasm` binary. And with which command did you generate it?

**Review by MaartenS11 — APPROVED** [review]

**Pull request merged**
