### PR TITLE
fix issue #168

### PR DESCRIPTION
**Pull request by carllocos**
solves issue https://github.com/TOPLLab/WARDuino/issues/168, which is one bug discussed in https://github.com/orgs/TOPLLab/discussions/1

### CODE REVIEW

**Review by tolauwae — CHANGES_REQUESTED** [review]
As I understand, the issue is that the `findOpcode` function was not updated to handle the guard blocks with opcodes `0xff` and `0xfe`. I think we should instead update this code, so that the blocks are the same as the others, and the dump function do not need to change at all.

**Comment by carllocos** [comment]
> I think we should instead update this code

what is 'this'? the `findOpcode`?

I do not understand what you are proposing. What do you mean by "so that blocks are the same as the others"? do you mean that findOpcode should also work upon any block despite the type of block?

If so, this would be unnecessary work since the findOpcode method was introduced to be solely used by the `woodDump` method when printing callstack information. The printed information is complete in the sense that it lets reconstruct the same callstack in another VM. At the moment of printing, getting access to block pointers of proxy and callback type is irrelevant since such blocks have to be newly allocated when reconstructing a callstack as per my explanation of bullet point 2 [issue](https://github.com/TOPLLab/WARDuino/issues/168#issue-1699910898)

**Comment by tolauwae** [comment]
Ah I did not know the `findOpCode` function was only used by the dumps. I understand what is going on better now.

> getting access to block pointers of proxy and callback type is irrelevant 

Because they don't point to code, right?

I was also confused about the else if that was added, I thought this was on the same side, but the `saveState` function confusingly doesn't save, but restores the state. So now the else if at least makes sense. It is still not very elegant, but than again the `saveState` function is already massive so let's not worry about it.

I think I can approve this PR, except for 1 minor detail:

I still don't understand why `findOpCode` can't just do the check for the guard blocks? Isn't it weird that it doesn't work for those blocks, and you have to put a ternary operator around it everytime you use it?

https://github.com/TOPLLab/WARDuino/blob/2a45d9c16a4ac36aeed71f759bfe0229464a03e9/src/Debug/debugger.cpp#L708-L710

**Comment by carllocos** [comment]
> Because they don't point to code, right?

Indeed. That is why `saveState` allocates new blocks when reconstructing the callstack for frames that point to callback or proxy call blocks.

Yes `saveState` needs serious refactoring. At least the name needs to change. Feel free to refactor. I also believe that findOpcode is also not well named, maybe better findBlock.

The lengthy `else if` also bothers me a lot but I fear that to properly clean that, we need to provide more abstractions which are best provided as a separate PR.

The ternary operator was to keep the FATAL of the `findOpcode` in place, which is useful to help debug. Recently the fatal helped me to for instance detect that wooddump and saveState did not account for the proxy and callback type blocks.

**Review by tolauwae — APPROVED** [review]
In that case the PR looks good. We can refactor some other time.

**Pull request merged**
